### ISSUE TITLE
dyld: Library not loaded: @rpath/libneko.2.dylib

### ISSUE THREAD

**Issue by imbsky** [asdf-community/asdf-haxe#4]
The haxelib command seems to require this Dynamic Library, which is not included in the files available for download from the haxe repository. So I created a plugin for neko that includes that Dynamic Library, but is there a good way to interoperate the haxe and neko plugins?

**Comment by imbsky** [comment]
CC: @vic

**Comment by vic** [comment]
Not really sure what's happening (I have no experience at all using haxe+neko) but from reading this issue: https://github.com/HaxeFoundation/neko/issues/98 it looks like you might want to try and set `NEKOPATH` to include the location of `libneko.2.dylib`. 

I'd recommend first trying to make the command work manually (try setting the PATH and NEKOPATH yourself to anything that works) and once you have that, you might want to create a `bin/exec_env` file for your plugin which can export environment variables needed by your plugin tools. Also you can provide `custom shims` (wrappers) around the shipped binaries that can try to determine the environment on behalf of the user.

For a working example, you might want to take a look at [asdf-elixir](https://github.com/asdf-vm/asdf-elixir) which has it's own `mix` shim (overriding the one distributed) and also exposes custom env on it's `bin/exec_env`.

Hope any of this can be of help.

**Comment by imbsky** [comment]
If the neko plugin exports `NEKOPATH` from `exec-env` as follows, will it be available from the haxe plugin?

```bash
#!/usr/bin/env bash

if [ "$NEKOPATH" = "" ]; then
  export NEKOPATH=$ASDF_INSTALL_PATH/bin
fi
```

**Comment by vic** [comment]
Hm, no.. In *normal* asdf (without something like `asdf-direnv`), the plugin's `exec-env` file is sourced just prior to executing a tools binary. In this case, if the snippet above is part of `neko-plugin/bin/exec-env` it will only be sourced prior execution of binaries from the neko plugin. 

What you want is `haxe-plugin/bin/exec-env` which would have to determine if there's an empty `NEKOPATH`, and if so, it should see if there's a current asdf-managed `neko` version available (perhaps using `asdf current neko` and trying to set `NEKOPATH` to the location of currently selected neko)

In the case of `asdf-direnv` all `exec-env` files are sourced just one, creating a big whole environment with everything set. But your plugin should not depend on `asdf-direnv` being used I guess.

**Comment by vic** [comment]
@imbsky Just pushed a quick-n-dirty PR for you :D. 

If you update your neko plugin, it now exports the NEKOPATH variable, and I'm trying to use that from this plugin.

**Comment by imbsky** [comment]
I have seen that `NEKOPATH` works well in other cases, but it does not seem to work with this dynamic library problem. Is there a way to enable the Haxe plugin to handle certain files under the Neko plugin's bin directory? I still don't understand correctly if shims can do that.

**Comment by vic** [comment]
Hm, maybe if you provide an example project I could reproduce the problem and get what you mean by `enable the Haxe plugin to handle certain files under Neko's bin directory`.

Could you provide an example of what's happening ?

**Comment by imbsky** [comment]
Ah, sorry, my English is not very good. For example, is it possible to have the neko's `libneko.2.dylib` in the haxe plugin's bin directory?

**Comment by imbsky** [comment]
It's better to pretend it exists rather than actually copying it, but it doesn't matter.

**Comment by vic** [comment]
Your English is pretty good :)

It's just that I'm not understanding the problem since I'm not a haxe+neko user and can't properly tell what's the best solution. Perhaps I should try using both of these plugins and try to reproduce the problem to better understand what's happenning.

Could you provide a minimal hello-world or something I could run with haxe+neko so that I can see that `libneko.2.dylib` problem?

**Comment by imbsky** [comment]
Thank you for your kind words! You will probably get the same problem just by running `haxelib version`.

**Comment by as790** [comment]
Hi 
Can yuo help meeeee

**Comment by Gi0rgi0s** [comment]
I am still seeing this issue, and yes I get it  just by running `haxelib version` 
While I can't tell you what version I'm using, I can tell you the md5 of the executable is **b468a2704b535080252a95a6aacd66d8**

**Comment by imbsky** [comment]
https://github.com/asdf-community/asdf-haxe#troubleshooting

**Comment by Gi0rgi0s** [comment]
@imbsky Thanks for the help. I'm sorry to say this isn't working for me. Your help is appreciated 👍

$ asdf current neko
`2.0.0    (set by /Users/****/.tool-versions)`
$ asdf current haxe
`3.4.7    (set by /Users/****/.tool-versions)`

$ asdf haxe neko dylibs link
`/Users/****/.asdf/installs/haxe/3.4.7/bin/libneko.dylib -> /Users/****/.asdf/installs/neko/2.0.0/bin/libneko.dylib`

$ which neko
`/Users/****/.asdf/shims/neko`
$ which haxe
`/Users/****/.asdf/shims/haxe`

$ sw_vers
`ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87`
